wheel_build_task:
  name: Build Rasterio wheels for Mac ARM64.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    BUILD_PREFIX: /tmp/local
    REPO_DIR: rasterio
    BUILD_COMMIT: 1.3.5
    CIRRUS_CLONE_SUBMODULES: true
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    PLAT: "arm64"
    BUILD_DEPENDS: "oldest-supported-numpy cython>=0.29 wheel==0.34.2"
    TEST_DEPENDS: "oldest-supported-numpy attrs==21.4.0 pytest==6.2.5 click==8.0.3 mock boto3 packaging hypothesis==4.38.1 wheel==0.34.2"
    TRAVIS_OS_NAME: "osx"
    MACOSX_DEPLOYMENT_TARGET: "10.10"
    MB_ML_VER: "2014"
    matrix:
      - MB_PYTHON_VERSION: "3.11"
  install_pre_requirements_script:
    - brew install python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
  brew_remove_pkgs_script:
    - brew remove -f --ignore-dependencies webp zstd xz libtiff libxcb curl php lcms2 xmlto ghostscript
  build_wheel_script:
    - mkdir -p $BUILD_PREFIX/include
    - mkdir -p $BUILD_PREFIX/lib
    - mkdir -p $BUILD_PREFIX/share
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - python3 -m pip install virtualenv
    - before_install
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT
  test_wheel_script:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - install_run $PLAT
  wheels_artifacts:
    path: "wheelhouse/*.whl"
