wheel_build_task:
  name: Build Rasterio wheels for Mac ARM64.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    REPO_DIR: rasterio
    BUILD_COMMIT: 1.3.5
    CIRRUS_CLONE_SUBMODULES: true
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    PLAT: "arm64"
    BUILD_PREFIX: $HOME/local
    BUILD_DEPENDS: "oldest-supported-numpy cython>=0.29 wheel==0.34.2"
    TEST_DEPENDS: "oldest-supported-numpy attrs==21.4.0 pytest==6.2.5 click==8.0.3 mock boto3 packaging hypothesis==4.38.1 wheel==0.34.2"
    TRAVIS_OS_NAME: "osx"
    MACOSX_DEPLOYMENT_TARGET: "10.10"
    MB_ML_VER: "2014"
    matrix:
      - MB_PYTHON_VERSION: "3.11"
  install_pre_requirements_script:
    - brew install python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
  build_wheel_script:
    - .github/workflows/build.sh
  wheels_artifacts:
    path: "wheelhouse/*.whl"
