wheel_build_task:
  name: Build Rasterio wheels for Mac ARM64.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    BUILD_PREFIX: /private/tmp/local
    REPO_DIR: rasterio
    BUILD_COMMIT: 1.3.9
    CIRRUS_CLONE_SUBMODULES: true
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    PLAT: "arm64"
    BUILD_DEPENDS: "setuptools oldest-supported-numpy cython~=3.0.2 wheel"
    TEST_DEPENDS: "oldest-supported-numpy attrs pytest click mock boto3 packaging hypothesis wheel"
    MACOSX_DEPLOYMENT_TARGET: "11.0"
    matrix:
      - MB_PYTHON_VERSION: "3.12"
      - MB_PYTHON_VERSION: "3.11"
      - MB_PYTHON_VERSION: "3.10"
      - MB_PYTHON_VERSION: "3.9"
      - MB_PYTHON_VERSION: "3.8"
  install_pre_requirements_script:
    - brew install pkg-config python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python
  brew_remove_pkgs_script:
    - brew remove -f --ignore-dependencies liblerc webp zstd libpng libtiff libxcb libxdmcp curl php lcms2 xmlto ghostscript lz4 openjpeg
  build_wheel_script:
    - mkdir -p $BUILD_PREFIX/include
    - mkdir -p $BUILD_PREFIX/lib/pkgconfig
    - mkdir -p $BUILD_PREFIX/bin
    - mkdir -p $BUILD_PREFIX/share/doc/
    - mkdir -p $BUILD_PREFIX/share/man/man{1,3,5,7}
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - python3 -m pip install virtualenv
    - before_install
    - clean_code $REPO_DIR $BUILD_COMMIT
    - MACOSX_DEPLOYMENT_TARGET=11.0
    - GDAL_CONFIG=$BUILD_PREFIX/bin/gdal-config
    - PROJ_LIB=$BUILD_PREFIX/share/proj
    - build_wheel $REPO_DIR $PLAT
  test_wheel_script:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - python3 -m pip install virtualenv
    - before_install
    - install_run $PLAT
  wheels_artifacts:
    path: "wheelhouse/*.whl"
